### ISSUE TITLE
Crash when using Biomes O' Plenty/ ore generation

### ISSUE THREAD

**Issue by cocopuffs99** [Flaxbeard/Flaxbeards-Steam-Power#231]
I get this crash when trying to start a new world with BOP (Biomes O Plenty) terrain generation-
seems like at least one part may be related to SteamcraftOreGen?  Any ideas?  Thanks. =)

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 3/10/15 9:43 PM
Description: Exception getting block type in world

java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at flaxbeard.steamcraft.world.SteamcraftOreGen.generate(SteamcraftOreGen.java:26)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:106)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
	at fastcraft.a.c.a(F:84)
	at fastcraft.Hooks.r(F:139)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.checkBlock(EventHandlerGC.java:420)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.doPopulate(EventHandlerGC.java:385)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.populate(EventHandlerGC.java:337)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_419_EventHandlerGC_populate_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:448)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at fastcraft.a.c.a(F:84)
	at fastcraft.Hooks.r(F:139)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.world.World.func_147437_c(World.java:365)
	at biomesoplenty.common.world.WorldProviderSurfaceBOP.getTopBlockCoord(WorldProviderSurfaceBOP.java:42)
	at biomesoplenty.common.world.WorldProviderSurfaceBOP.func_76566_a(WorldProviderSurfaceBOP.java:14)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)
	at WorldServerOF.func_72963_a(WorldServerOF.java:80)
	at net.minecraft.world.World.<init>(World.java:260)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at WorldServerOF.<init>(WorldServerOF.java:69)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by xbony2** [comment]
I think this might be connected with #224.

**Comment by xbony2** [comment]
Er, #230.

**Comment by xbony2** [comment]
Yeah, I think it's the same thing. Santa should fix the issue.

**Comment by elifoster** [comment]
Yeah, that has nothing to do with BoP. Duplicate of #230.
