### ISSUE TITLE
Crash using updated Computercraft 1.73

### ISSUE THREAD

**Issue by Tomatoh** [Flaxbeard/Flaxbeards-Steam-Power#240]
java.lang.NumberFormatException: For input string: ""

	at java.lang.NumberFormatException.forInputString(Unknown Source)

	at java.lang.Integer.parseInt(Unknown Source)

	at java.lang.Integer.parseInt(Unknown Source)

	at flaxbeard.steamcraft.world.SteamcraftOreGen.generate(SteamcraftOreGen.java:26)

	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:106)

	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)

	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045)

	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)

	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)

	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)

	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)

	at net.minecraft.world.World.func_72964_e(World.java:419)

	at net.minecraft.world.World.func_147439_a(World.java:345)

	at net.minecraft.block.BlockGrass.func_149674_a(BlockGrass.java:57)

	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:391)

	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)

	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)

	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)

	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)

	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)

	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by xbony2** [comment]
Doesn't have to do with updating the mod. Pretty sure this is same issue as #230
